# Module: SQLite3 Assignments
## Lesson: SQLite3
### Assignment 1: Creating and Connecting to a Database

1. Write a Python function to create a new SQLite3 database named `test.db`.
2. Write a Python function to create a table named `employees` with columns `id` (integer), `name` (text), `age` (integer), and `department` (text) in the `test.db` database.

### Assignment 2: Inserting Data

1. Write a Python function to insert a new employee into the `employees` table.
2. Insert at least 5 different employees into the `employees` table.

### Assignment 3: Querying Data

1. Write a Python function to fetch and display all records from the `employees` table.
2. Write a Python function to fetch and display all employees from a specific department.

### Assignment 4: Updating Data

1. Write a Python function to update the department of an employee based on their `id`.
2. Update the department of at least 2 employees and display the updated records.

### Assignment 5: Deleting Data

1. Write a Python function to delete an employee from the `employees` table based on their `id`.
2. Delete at least 1 employee and display the remaining records.

### Assignment 6: Advanced Queries

1. Write a Python function to fetch and display employees older than a certain age.
2. Write a Python function to fetch and display employees whose names start with a specific letter.

### Assignment 7: Handling Transactions

1. Write a Python function to insert multiple employees into the `employees` table in a single transaction. Ensure that if any insertion fails, none of the insertions are committed.
2. Write a Python function to update the age of multiple employees in a single transaction. Ensure that if any update fails, none of the updates are committed.

### Assignment 8: Creating Relationships

1. Create a new table named `departments` with columns `id` (integer) and `name` (text).
2. Modify the `employees` table to include a foreign key referencing the `id` column in the `departments` table.
3. Write a Python function to insert data into both the `departments` and `employees` tables, ensuring referential integrity.

### Assignment 9: Indexing and Optimization

1. Create an index on the `name` column of the `employees` table.
2. Write a Python function to fetch and display all employees whose names start with a specific letter. Compare the performance with and without the index.

### Assignment 10: Backing Up and Restoring Data

1. Write a Python function to back up the `test.db` database to a file named `backup.db`.
2. Write a Python function to restore the `test.db` database from the `backup.db` file.

In [ ]:

connection= sqlite3.connect('test.db')
cursor = connection.cursor()
cursor.execute("DROP TABLE IF EXISTS employees")

In [ ]:
## Assignment 1: Creating and Connecting to a Database
import sqlite3
# 1. Write a Python function to create a new SQLite3 database named `test.db`.

def create_database():    
    conn= sqlite3.connect('test.db')
    conn.close()
    print("Database created and Succesfully connected.")

# 2. Write a Python function to create a table named `employees` with columns `id` (integer), `name` (text), 
# `age` (integer), and `department` (text) in the `test.db` database.

def create_table():
    connection= sqlite3.connect('test.db')
    cursor = connection.cursor()
    cursor.execute(
        '''
        CREATE TABLE If not Exists employees (
            id Integer Primary Key,
            name text not null,
            age Int,
            department text
        )   
    ''')
    connection.commit()
    connection.close()
    print("Table 'employees' created successfully ")

create_database()
create_table()

In [ ]:
### Assignment 2: Inserting Data

# 1. Write a Python function to insert a new employee into the `employees` table.
def insert_employee(id, name, age, department):
    conn = sqlite3.connect('test.db')
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO employees (id, name, age, department)
        VALUES (?, ?, ?, ?)
    ''', (id, name, age, department))
    conn.commit()
    conn.close()
    print("Employee inserted successfully.")

# Test the function
insert_employee(1, 'Alice', 30, 'HR')

# # 2. Insert at least 5 different employees into the `employees` table.
# def insert():

insert_employee(2, "ABC", 21, "IT")
insert_employee(3, "DEF", 25, "CALL")
insert_employee(4, "QWE", 31, "DS")
insert_employee(5, "RTY", 45, "CEO")
insert_employee(6, "UIO", 29, "IT")

In [ ]:
### Assignment 3: Querying Data

# 1. Write a Python function to fetch and display all records from the `employees` table.
def show_employee():
    connection = sqlite3.connect('test.db')
    cursor = connection.cursor()
    cursor.execute("Select * from employees")
    rows = cursor.fetchall()
    connection.close()
    for row in rows:
        print(row)

#Testing the function
show_employee()

# 2. Write a Python function to fetch and display all employees from a specific department.
def fetch_employee_by_department(department):
    connection = sqlite3.connect('test.db')
    cursor = connection.cursor()
    cursor.execute("Select * from employees WHERE department = ?", (department,))
    records= cursor.fetchall()
    connection.close()

    for record in records:
        print(record)

#Testing the funtion
fetch_employee_by_department('HR')

In [ ]:
### Assignment 4: Updating Data

# 1. Write a Python function to update the department of an employee based on their `id`.
def change_department(id, new_department):
    connection = sqlite3.connect('test.db')
    cursor = connection.cursor()
    cursor.execute('''
    UPDATE employees
    SET department =?
    where id = ?
''', (new_department, id))
    connection.commit()
    connection.close()
    print("Employee department updated successfully.")

# 2. Update the department of at least 2 employees and display the updated records.
change_department(1, "RnD")
change_department(5, 'CFO')

In [ ]:
show_employee()

In [ ]:
### Assignment 5: Deleting Data

# 1. Write a Python function to delete an employee from the `employees` table based on their `id`.
def delete_employee(id):
    connection = sqlite3.connect('test.db')
    cursor = connection.cursor()
    cursor.execute('''
    DELETE from employees 
    where id = ?
    ''', (id,))
    connection.commit()
    connection.close()
    print(f"Employee with id{id} is deleted successfully")

# 2. Delete at least 1 employee and display the remaining records.
delete_employee(4)
show_employee()

In [ ]:
## Assignment 6: Advanced Queries

# 1. Write a Python function to fetch and display employees older than a certain age.
def fetch_employee_older_than(age):
    connection= sqlite3.connect('test.db')
    cursor = connection.cursor()
    cursor.execute('''
    SELECT * from employees 
    Where age > ?
    ''', (age,))
    records= cursor.fetchall()
    connection.close()
    for record in records:
        print(record)

#Testing the function
fetch_employee_older_than(25)

In [ ]:
# 2. Write a Python function to fetch and display employees whose names start with a specific letter.
def fetch_employee_name_start_with(letter):
    connection = sqlite3.connect('test.db')
    cursor= connection.cursor()
    cursor.execute('SELECT * from employees WHERE name Like ?',(letter+ '%',))
    records = cursor.fetchall()

    for record in records:
        print(record)

#Testing the function
fetch_employee_name_start_with('A')

In [ ]:
## Assignment 7: Handling Transactions

# 1. Write a Python function to insert multiple employees into the `employees` table in a single transaction.
# Ensure that if any insertion fails, none of the insertions are committed.
def insert_multiple_employee(employee):
    connection = sqlite3.connect('test.db')
    cursor= connection.cursor()
    try:
        cursor.executemany('''
        Insert into employees(id, name, age, department)
                        values(?,?,?,?)
        ''', employee)
        connection.commit()
        print("All the employees inserted Successfully.")
    except Exception as e:
        connection.rollback()
        print("Error occured, Transaction rolled back.")
        print(e)
    finally:
        connection.close()


# Test the function with valid and invalid data
employees = [
    (11, 'Frank', 40, 'Finance'),
    (10, 'Grace', 29, 'Engineering'),
    (8, 'Hannah', 35, 'Marketing'),
    (9, 'Ivan', 38, 'Sales'),
    # (6, 'Jack', 45, 'HR')  # Duplicate ID to cause an error
]
insert_multiple_employee(employees)

In [ ]:
show_employee()

In [ ]:

# 2. Write a Python function to update the age of multiple employees in a single transaction. 
# Ensure that if any update fails, none of the updates are committed.

def update_multiple_employee_age(updates):
    connection = sqlite3.connect('test.db')
    cursor= connection.cursor()
    try:
        cursor.executemany('''
        UPDATE employees
        SET age = ?
        WHERE id = ?
        ''', updates)
        connection.commit()
        print("All the employees age is Changed Successfully.")
    except Exception as e:
        connection.rollback()
        print("Error occured, Transaction rolled back.")
        print(e)
    finally:
        connection.close()
    
updates =[
    (35, 1),
    (27, 2), 
    (29, 7)
]

update_multiple_employee_age(updates)

In [ ]:
### Assignment 8: Creating Relationships

# 1. Create a new table named `departments` with columns `id` (integer) and `name` (text).

def create_departement():
    Connection = sqlite3.connect('test.db')
    cursor= connection.cursor()
    cursor.execute(
        '''
        CREATE TABLE IF NOT EXISTS departments(
        id INTEGER,
        name TEXT
        )
        ''')
    connection.commit()
    connection.close()

In [ ]:
# 2. Modify the `employees` table to include a foreign key referencing the `id` column in the `departments` table.
def add_department_foreign_key():
    conn = sqlite3.connect('test.db')
    cursor = conn.cursor()
    cursor.execute('''
        PRAGMA foreign_keys=off;
        BEGIN TRANSACTION;
        ALTER TABLE employees RENAME TO old_employees;
        CREATE TABLE employees (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            age INTEGER,
            department TEXT,
            department_id INTEGER,
            FOREIGN KEY(department_id) REFERENCES departments(id) 
        );
        INSERT INTO employees (id, name, age, department)
        SELECT id, name, age, department FROM old_employees;
        DROP TABLE old_employees;
        COMMIT;
        PRAGMA foreign_keys=on;
    ''')
    conn.commit()
    conn.close()
    print("Table 'employees' modified successfully.")

# Test the function
add_department_foreign_key()

In [ ]:
# 3. Write a Python function to insert data into both the `departments` and `employees` tables, 
# ensuring referential integrity.

def insert_in_department_and_employees(department_id, department_name, employee_id, name, age, department):
    conn = sqlite3.connect('test.db')
    cursor = conn.cursor()
    try:
        cursor.execute('''
            INSERT INTO departments (id, name)
            VALUES (?, ?)
        ''', (department_id, department_name))
        cursor.execute('''
            INSERT INTO employees (id, name, age, department)
            VALUES (?, ?, ?, ?)
        ''', (employee_id, name, age, department))
        conn.commit()
        print("Department and employee inserted successfully.")
    except Exception as e:
        conn.rollback()
        print("Error occurred, transaction rolled back.")
        print(e)
    finally:
        conn.close()

insert_in_department_and_employees(1, 'Finance', 13, 'Zara', 28, 'Finance')

In [ ]:
### Assignment 9: Indexing and Optimization

# 1. Create an index on the `name` column of the `employees` table.
def index_on_name():
    connection = sqlite3.connect('test.db')
    cursor= connection.cursor()
    cursor.execute('CREATE INDEX idx_name ')

In [ ]:
# 2. Write a Python function to fetch and display all employees whose names start with a specific letter. 
# Compare the performance with and without the index.

import time

def fetch_employees_name_starts_with_performance(letter):
    conn = sqlite3.connect('test.db')
    cursor = conn.cursor()
    start_time = time.time()
    cursor.execute('SELECT * FROM employees WHERE name LIKE ?', (letter + '%',))
    records = cursor.fetchall()
    end_time = time.time()
    conn.close()
    print("Time taken: {} seconds".format(end_time - start_time))
    for record in records:
        print(record)

# Test the function with the index
fetch_employees_name_starts_with_performance('A')

In [ ]:
### Assignment 10: Backing Up and Restoring Data

# 1. Write a Python function to back up the `test.db` database to a file named `backup.db`.

import shutil

def backup_database():
    shutil.copy('test.db', 'backup.db')
    print("Database backed up successfully.")

# Test the function
backup_database()

# 2. Write a Python function to restore the `test.db` database from the `backup.db` file.
def restore_database():
    shutil.copy('backup.db', 'test.db')
    print("Database restored successfully.")

# Test the function
restore_database()